[project]
name = "ai-python"
version = "0.1.0"
description = "AI Content Python Service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.0",
    "fastapi>=0.142.2",
    "google-genai>=2.28.0",
    "python-dotenv>=1.2.4",
    "uvicorn>=0.54.0",
]

[project.scripts]
ai-python = "ai_python:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""